### ISSUE TITLE
Issues #1&2: Technical

### ISSUE THREAD

**Issue by LleytonHornig** [lexifortune/Project-Repository#7]
Issue #1: You do not have any valid links on your NAV bar, so essentially it is just your index page for content. The right-hand side of the NAV bar also does not have links to click on for the "subscribe" "search" and "account", so I would recommend adding those as well.

Issue #2: In line 71 of your index.css, you can use `margin-left: auto` and `margin-right: auto` instead of text-align for your videos.

**Comment by lexifortune** [comment]
Fixed it! Thank you!
